/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Scheduler BE — spec di riferimento (NON autoritativo)
 * Spec minimo di riferimento per sbloccare lo sviluppo frontend quando il backend non e\' ancora disponibile. NON e\' la fonte di verita\': appena il backend espone /openapi.json, questo file va abbandonato in favore di quello reale. I nomi dei campi qui riflettono le fixture in mocks/fixtures/, derivate dai dati di seed del backend.
 *
 * The version of the OpenAPI document: 0.0.0-reference
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { AuthResponse, LoginInput, RegisterInput } from '../models/index';
import {
  AuthResponseFromJSON,
  LoginInputToJSON,
  RegisterInputToJSON,
} from '../models/index';

export interface AuthLoginPostRequest {
  loginInput: LoginInput;
}

export interface AuthRegisterPostRequest {
  registerInput: RegisterInput;
}

/**
 *
 */
export class AuthApi extends runtime.BaseAPI {
  /**
   * Login
   */
  async authLoginPostRaw(
    requestParameters: AuthLoginPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<AuthResponse>> {
    if (requestParameters['loginInput'] == null) {
      throw new runtime.RequiredError(
        'loginInput',
        'Required parameter "loginInput" was null or undefined when calling authLoginPost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/auth/login`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: LoginInputToJSON(requestParameters['loginInput']),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AuthResponseFromJSON(jsonValue)
    );
  }

  /**
   * Login
   */
  async authLoginPost(
    requestParameters: AuthLoginPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<AuthResponse> {
    const response = await this.authLoginPostRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Registrazione di un nuovo cliente
   */
  async authRegisterPostRaw(
    requestParameters: AuthRegisterPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<AuthResponse>> {
    if (requestParameters['registerInput'] == null) {
      throw new runtime.RequiredError(
        'registerInput',
        'Required parameter "registerInput" was null or undefined when calling authRegisterPost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/auth/register`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: RegisterInputToJSON(requestParameters['registerInput']),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AuthResponseFromJSON(jsonValue)
    );
  }

  /**
   * Registrazione di un nuovo cliente
   */
  async authRegisterPost(
    requestParameters: AuthRegisterPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<AuthResponse> {
    const response = await this.authRegisterPostRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}
