/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Scheduler BE — spec di riferimento (NON autoritativo)
 * Spec minimo di riferimento per sbloccare lo sviluppo frontend quando il backend non e\' ancora disponibile. NON e\' la fonte di verita\': appena il backend espone /openapi.json, questo file va abbandonato in favore di quello reale. I nomi dei campi qui riflettono le fixture in mocks/fixtures/, derivate dai dati di seed del backend.
 *
 * The version of the OpenAPI document: 0.0.0-reference
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { HealthGet200Response } from '../models/index';
import {
  HealthGet200ResponseFromJSON,
  HealthGet200ResponseToJSON,
} from '../models/index';

/**
 *
 */
export class DefaultApi extends runtime.BaseAPI {
  /**
   * Health check
   */
  async healthGetRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<HealthGet200Response>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/health`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      HealthGet200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Health check
   */
  async healthGet(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<HealthGet200Response> {
    const response = await this.healthGetRaw(initOverrides);
    return await response.value();
  }
}
