/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Scheduler BE — spec di riferimento (NON autoritativo)
 * Spec minimo di riferimento per sbloccare lo sviluppo frontend quando il backend non e\' ancora disponibile. NON e\' la fonte di verita\': appena il backend espone /openapi.json, questo file va abbandonato in favore di quello reale. I nomi dei campi qui riflettono le fixture in mocks/fixtures/, derivate dai dati di seed del backend.
 *
 * The version of the OpenAPI document: 0.0.0-reference
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  ErrorResponse,
  Film,
  FilmInput,
  FilmsGet200Response,
} from '../models/index';
import {
  ErrorResponseFromJSON,
  ErrorResponseToJSON,
  FilmFromJSON,
  FilmToJSON,
  FilmInputFromJSON,
  FilmInputToJSON,
  FilmsGet200ResponseFromJSON,
  FilmsGet200ResponseToJSON,
} from '../models/index';

export interface FilmsGetRequest {
  page?: number;
  pageSize?: number;
}

export interface FilmsIdDeleteRequest {
  id: number;
}

export interface FilmsIdGetRequest {
  id: number;
}

export interface FilmsIdPatchRequest {
  id: number;
  filmInput: FilmInput;
}

export interface FilmsPostRequest {
  filmInput: FilmInput;
}

/**
 *
 */
export class FilmApi extends runtime.BaseAPI {
  /**
   * Elenco film
   */
  async filmsGetRaw(
    requestParameters: FilmsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<FilmsGet200Response>> {
    const queryParameters: any = {};

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page'];
    }

    if (requestParameters['pageSize'] != null) {
      queryParameters['pageSize'] = requestParameters['pageSize'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/films`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      FilmsGet200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Elenco film
   */
  async filmsGet(
    requestParameters: FilmsGetRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<FilmsGet200Response> {
    const response = await this.filmsGetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Elimina un film (admin)
   */
  async filmsIdDeleteRaw(
    requestParameters: FilmsIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling filmsIdDelete().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearerAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/films/{id}`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters['id']))
        ),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Elimina un film (admin)
   */
  async filmsIdDelete(
    requestParameters: FilmsIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.filmsIdDeleteRaw(requestParameters, initOverrides);
  }

  /**
   * Dettaglio film
   */
  async filmsIdGetRaw(
    requestParameters: FilmsIdGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Film>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling filmsIdGet().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/films/{id}`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters['id']))
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      FilmFromJSON(jsonValue)
    );
  }

  /**
   * Dettaglio film
   */
  async filmsIdGet(
    requestParameters: FilmsIdGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Film> {
    const response = await this.filmsIdGetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Aggiorna un film (admin)
   */
  async filmsIdPatchRaw(
    requestParameters: FilmsIdPatchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Film>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling filmsIdPatch().'
      );
    }

    if (requestParameters['filmInput'] == null) {
      throw new runtime.RequiredError(
        'filmInput',
        'Required parameter "filmInput" was null or undefined when calling filmsIdPatch().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearerAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/films/{id}`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters['id']))
        ),
        method: 'PATCH',
        headers: headerParameters,
        query: queryParameters,
        body: FilmInputToJSON(requestParameters['filmInput']),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      FilmFromJSON(jsonValue)
    );
  }

  /**
   * Aggiorna un film (admin)
   */
  async filmsIdPatch(
    requestParameters: FilmsIdPatchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Film> {
    const response = await this.filmsIdPatchRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Crea un film (admin)
   */
  async filmsPostRaw(
    requestParameters: FilmsPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Film>> {
    if (requestParameters['filmInput'] == null) {
      throw new runtime.RequiredError(
        'filmInput',
        'Required parameter "filmInput" was null or undefined when calling filmsPost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearerAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/films`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: FilmInputToJSON(requestParameters['filmInput']),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      FilmFromJSON(jsonValue)
    );
  }

  /**
   * Crea un film (admin)
   */
  async filmsPost(
    requestParameters: FilmsPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Film> {
    const response = await this.filmsPostRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
