/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Scheduler BE — spec di riferimento (NON autoritativo)
 * Spec minimo di riferimento per sbloccare lo sviluppo frontend quando il backend non e\' ancora disponibile. NON e\' la fonte di verita\': appena il backend espone /openapi.json, questo file va abbandonato in favore di quello reale. I nomi dei campi qui riflettono le fixture in mocks/fixtures/, derivate dai dati di seed del backend.
 *
 * The version of the OpenAPI document: 0.0.0-reference
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  Prenotazione,
  ProiezioniIdPrenotazioniPostRequest,
} from '../models/index';
import {
  PrenotazioneFromJSON,
  ProiezioniIdPrenotazioniPostRequestToJSON,
} from '../models/index';

export interface PrenotazioniIdDeleteRequest {
  id: number;
}

export interface ProiezioniIdPrenotazioniPostOperationRequest {
  id: number;
  proiezioniIdPrenotazioniPostRequest: ProiezioniIdPrenotazioniPostRequest;
}

/**
 *
 */
export class PrenotazioniApi extends runtime.BaseAPI {
  /**
   * Prenotazioni dell\'utente autenticato
   */
  async prenotazioniGetRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<Prenotazione>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearerAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/prenotazioni`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(PrenotazioneFromJSON)
    );
  }

  /**
   * Prenotazioni dell\'utente autenticato
   */
  async prenotazioniGet(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<Prenotazione>> {
    const response = await this.prenotazioniGetRaw(initOverrides);
    return await response.value();
  }

  /**
   * Consentito solo fino a CANCELLATION_DEADLINE_HOURS (default 3) ore prima dell\'inizio dello spettacolo.
   * Cancella una prenotazione
   */
  async prenotazioniIdDeleteRaw(
    requestParameters: PrenotazioniIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling prenotazioniIdDelete().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearerAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/prenotazioni/{id}`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters['id']))
        ),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Consentito solo fino a CANCELLATION_DEADLINE_HOURS (default 3) ore prima dell\'inizio dello spettacolo.
   * Cancella una prenotazione
   */
  async prenotazioniIdDelete(
    requestParameters: PrenotazioniIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.prenotazioniIdDeleteRaw(requestParameters, initOverrides);
  }

  /**
   * Prenota uno o piu\' posti
   */
  async proiezioniIdPrenotazioniPostRaw(
    requestParameters: ProiezioniIdPrenotazioniPostOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Prenotazione>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling proiezioniIdPrenotazioniPost().'
      );
    }

    if (requestParameters['proiezioniIdPrenotazioniPostRequest'] == null) {
      throw new runtime.RequiredError(
        'proiezioniIdPrenotazioniPostRequest',
        'Required parameter "proiezioniIdPrenotazioniPostRequest" was null or undefined when calling proiezioniIdPrenotazioniPost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearerAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/proiezioni/{id}/prenotazioni`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters['id']))
        ),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: ProiezioniIdPrenotazioniPostRequestToJSON(
          requestParameters['proiezioniIdPrenotazioniPostRequest']
        ),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PrenotazioneFromJSON(jsonValue)
    );
  }

  /**
   * Prenota uno o piu\' posti
   */
  async proiezioniIdPrenotazioniPost(
    requestParameters: ProiezioniIdPrenotazioniPostOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Prenotazione> {
    const response = await this.proiezioniIdPrenotazioniPostRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}
