/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Scheduler BE — spec di riferimento (NON autoritativo)
 * Spec minimo di riferimento per sbloccare lo sviluppo frontend quando il backend non e\' ancora disponibile. NON e\' la fonte di verita\': appena il backend espone /openapi.json, questo file va abbandonato in favore di quello reale. I nomi dei campi qui riflettono le fixture in mocks/fixtures/, derivate dai dati di seed del backend.
 *
 * The version of the OpenAPI document: 0.0.0-reference
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  DisponibilitaPosti,
  ErrorResponse,
  OccupazioneProiezione,
  Proiezione,
  ProiezioneInput,
} from '../models/index';
import {
  DisponibilitaPostiFromJSON,
  DisponibilitaPostiToJSON,
  ErrorResponseFromJSON,
  ErrorResponseToJSON,
  OccupazioneProiezioneFromJSON,
  OccupazioneProiezioneToJSON,
  ProiezioneFromJSON,
  ProiezioneToJSON,
  ProiezioneInputFromJSON,
  ProiezioneInputToJSON,
} from '../models/index';

export interface ProiezioniGetRequest {
  cinemaId?: number;
  data?: Date;
  filmId?: number;
  salaId?: number;
}

export interface ProiezioniIdDeleteRequest {
  id: number;
}

export interface ProiezioniIdGetRequest {
  id: number;
}

export interface ProiezioniIdPostiGetRequest {
  id: number;
}

export interface ProiezioniPostRequest {
  proiezioneInput: ProiezioneInput;
}

export interface ReportOccupazioneGetRequest {
  cinemaId: number;
  mese: number;
  anno: number;
}

/**
 *
 */
export class ProiezioniApi extends runtime.BaseAPI {
  /**
   * Palinsesto filtrabile
   */
  async proiezioniGetRaw(
    requestParameters: ProiezioniGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<Proiezione>>> {
    const queryParameters: any = {};

    if (requestParameters['cinemaId'] != null) {
      queryParameters['cinemaId'] = requestParameters['cinemaId'];
    }

    if (requestParameters['data'] != null) {
      queryParameters['data'] = (requestParameters['data'] as any)
        .toISOString()
        .substring(0, 10);
    }

    if (requestParameters['filmId'] != null) {
      queryParameters['filmId'] = requestParameters['filmId'];
    }

    if (requestParameters['salaId'] != null) {
      queryParameters['salaId'] = requestParameters['salaId'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/proiezioni`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(ProiezioneFromJSON)
    );
  }

  /**
   * Palinsesto filtrabile
   */
  async proiezioniGet(
    requestParameters: ProiezioniGetRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<Proiezione>> {
    const response = await this.proiezioniGetRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Elimina una proiezione (admin)
   */
  async proiezioniIdDeleteRaw(
    requestParameters: ProiezioniIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling proiezioniIdDelete().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearerAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/proiezioni/{id}`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters['id']))
        ),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Elimina una proiezione (admin)
   */
  async proiezioniIdDelete(
    requestParameters: ProiezioniIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.proiezioniIdDeleteRaw(requestParameters, initOverrides);
  }

  /**
   * Dettaglio proiezione
   */
  async proiezioniIdGetRaw(
    requestParameters: ProiezioniIdGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Proiezione>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling proiezioniIdGet().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/proiezioni/{id}`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters['id']))
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ProiezioneFromJSON(jsonValue)
    );
  }

  /**
   * Dettaglio proiezione
   */
  async proiezioniIdGet(
    requestParameters: ProiezioniIdGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Proiezione> {
    const response = await this.proiezioniIdGetRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Disponibilita\' dei posti per una proiezione
   */
  async proiezioniIdPostiGetRaw(
    requestParameters: ProiezioniIdPostiGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<DisponibilitaPosti>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling proiezioniIdPostiGet().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/proiezioni/{id}/posti`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters['id']))
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      DisponibilitaPostiFromJSON(jsonValue)
    );
  }

  /**
   * Disponibilita\' dei posti per una proiezione
   */
  async proiezioniIdPostiGet(
    requestParameters: ProiezioniIdPostiGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<DisponibilitaPosti> {
    const response = await this.proiezioniIdPostiGetRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Crea una proiezione (admin)
   */
  async proiezioniPostRaw(
    requestParameters: ProiezioniPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Proiezione>> {
    if (requestParameters['proiezioneInput'] == null) {
      throw new runtime.RequiredError(
        'proiezioneInput',
        'Required parameter "proiezioneInput" was null or undefined when calling proiezioniPost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearerAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/proiezioni`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: ProiezioneInputToJSON(requestParameters['proiezioneInput']),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ProiezioneFromJSON(jsonValue)
    );
  }

  /**
   * Crea una proiezione (admin)
   */
  async proiezioniPost(
    requestParameters: ProiezioniPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Proiezione> {
    const response = await this.proiezioniPostRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Report di occupazione mensile per sala (admin)
   */
  async reportOccupazioneGetRaw(
    requestParameters: ReportOccupazioneGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<OccupazioneProiezione>>> {
    if (requestParameters['cinemaId'] == null) {
      throw new runtime.RequiredError(
        'cinemaId',
        'Required parameter "cinemaId" was null or undefined when calling reportOccupazioneGet().'
      );
    }

    if (requestParameters['mese'] == null) {
      throw new runtime.RequiredError(
        'mese',
        'Required parameter "mese" was null or undefined when calling reportOccupazioneGet().'
      );
    }

    if (requestParameters['anno'] == null) {
      throw new runtime.RequiredError(
        'anno',
        'Required parameter "anno" was null or undefined when calling reportOccupazioneGet().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters['cinemaId'] != null) {
      queryParameters['cinemaId'] = requestParameters['cinemaId'];
    }

    if (requestParameters['mese'] != null) {
      queryParameters['mese'] = requestParameters['mese'];
    }

    if (requestParameters['anno'] != null) {
      queryParameters['anno'] = requestParameters['anno'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearerAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/report/occupazione`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(OccupazioneProiezioneFromJSON)
    );
  }

  /**
   * Report di occupazione mensile per sala (admin)
   */
  async reportOccupazioneGet(
    requestParameters: ReportOccupazioneGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<OccupazioneProiezione>> {
    const response = await this.reportOccupazioneGetRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}
