/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Scheduler BE — spec di riferimento (NON autoritativo)
 * Spec minimo di riferimento per sbloccare lo sviluppo frontend quando il backend non e\' ancora disponibile. NON e\' la fonte di verita\': appena il backend espone /openapi.json, questo file va abbandonato in favore di quello reale. I nomi dei campi qui riflettono le fixture in mocks/fixtures/, derivate dai dati di seed del backend.
 *
 * The version of the OpenAPI document: 0.0.0-reference
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { Sala } from '../models/index';
import { SalaFromJSON } from '../models/index';

export interface CinemasCinemaIdSaleGetRequest {
  cinemaId: number;
}

/**
 *
 */
export class SaleApi extends runtime.BaseAPI {
  /**
   * Elenco sale di un cinema
   */
  async cinemasCinemaIdSaleGetRaw(
    requestParameters: CinemasCinemaIdSaleGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<Sala>>> {
    if (requestParameters['cinemaId'] == null) {
      throw new runtime.RequiredError(
        'cinemaId',
        'Required parameter "cinemaId" was null or undefined when calling cinemasCinemaIdSaleGet().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/cinemas/{cinemaId}/sale`.replace(
          `{${'cinemaId'}}`,
          encodeURIComponent(String(requestParameters['cinemaId']))
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(SalaFromJSON)
    );
  }

  /**
   * Elenco sale di un cinema
   */
  async cinemasCinemaIdSaleGet(
    requestParameters: CinemasCinemaIdSaleGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<Sala>> {
    const response = await this.cinemasCinemaIdSaleGetRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}
