/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Scheduler BE — spec di riferimento (NON autoritativo)
 * Spec minimo di riferimento per sbloccare lo sviluppo frontend quando il backend non e\' ancora disponibile. NON e\' la fonte di verita\': appena il backend espone /openapi.json, questo file va abbandonato in favore di quello reale. I nomi dei campi qui riflettono le fixture in mocks/fixtures/, derivate dai dati di seed del backend.
 *
 * The version of the OpenAPI document: 0.0.0-reference
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Utente } from './Utente';
import { UtenteFromJSON, UtenteToJSON } from './Utente';

/**
 *
 * @export
 * @interface AuthResponse
 */
export interface AuthResponse {
  /**
   *
   * @type {string}
   * @memberof AuthResponse
   */
  token: string;
  /**
   *
   * @type {Utente}
   * @memberof AuthResponse
   */
  utente: Utente;
}

/**
 * Check if a given object implements the AuthResponse interface.
 */
export function instanceOfAuthResponse(value: object): value is AuthResponse {
  if (!('token' in value) || value['token'] === undefined) return false;
  return !(!('utente' in value) || value['utente'] === undefined);
}

export function AuthResponseFromJSON(json: any): AuthResponse {
  return AuthResponseFromJSONTyped(json, false);
}

export function AuthResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AuthResponse {
  if (json == null) {
    return json;
  }
  return {
    token: json['token'],
    utente: UtenteFromJSON(json['utente']),
  };
}

export function AuthResponseToJSON(json: any): AuthResponse {
  return AuthResponseToJSONTyped(json, false);
}

export function AuthResponseToJSONTyped(
  value?: AuthResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    token: value['token'],
    utente: UtenteToJSON(value['utente']),
  };
}
