/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Scheduler BE — spec di riferimento (NON autoritativo)
 * Spec minimo di riferimento per sbloccare lo sviluppo frontend quando il backend non e\' ancora disponibile. NON e\' la fonte di verita\': appena il backend espone /openapi.json, questo file va abbandonato in favore di quello reale. I nomi dei campi qui riflettono le fixture in mocks/fixtures/, derivate dai dati di seed del backend.
 *
 * The version of the OpenAPI document: 0.0.0-reference
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Posto } from './Posto';
import { PostoFromJSON, PostoToJSON } from './Posto';

/**
 *
 * @export
 * @interface DisponibilitaPosti
 */
export interface DisponibilitaPosti {
  /**
   *
   * @type {number}
   * @memberof DisponibilitaPosti
   */
  proiezioneId: number;
  /**
   *
   * @type {number}
   * @memberof DisponibilitaPosti
   */
  righe: number;
  /**
   *
   * @type {number}
   * @memberof DisponibilitaPosti
   */
  colonne: number;
  /**
   *
   * @type {Array<Posto>}
   * @memberof DisponibilitaPosti
   */
  postiOccupati: Array<Posto>;
}

/**
 * Check if a given object implements the DisponibilitaPosti interface.
 */
export function instanceOfDisponibilitaPosti(
  value: object
): value is DisponibilitaPosti {
  if (!('proiezioneId' in value) || value['proiezioneId'] === undefined)
    return false;
  if (!('righe' in value) || value['righe'] === undefined) return false;
  if (!('colonne' in value) || value['colonne'] === undefined) return false;
  return !(!('postiOccupati' in value) || value['postiOccupati'] === undefined);
}

export function DisponibilitaPostiFromJSON(json: any): DisponibilitaPosti {
  return DisponibilitaPostiFromJSONTyped(json, false);
}

export function DisponibilitaPostiFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DisponibilitaPosti {
  if (json == null) {
    return json;
  }
  return {
    proiezioneId: json['proiezioneId'],
    righe: json['righe'],
    colonne: json['colonne'],
    postiOccupati: (json['postiOccupati'] as Array<any>).map(PostoFromJSON),
  };
}

export function DisponibilitaPostiToJSON(json: any): DisponibilitaPosti {
  return DisponibilitaPostiToJSONTyped(json, false);
}

export function DisponibilitaPostiToJSONTyped(
  value?: DisponibilitaPosti | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    proiezioneId: value['proiezioneId'],
    righe: value['righe'],
    colonne: value['colonne'],
    postiOccupati: (value['postiOccupati'] as Array<any>).map(PostoToJSON),
  };
}
