/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Scheduler BE — spec di riferimento (NON autoritativo)
 * Spec minimo di riferimento per sbloccare lo sviluppo frontend quando il backend non e\' ancora disponibile. NON e\' la fonte di verita\': appena il backend espone /openapi.json, questo file va abbandonato in favore di quello reale. I nomi dei campi qui riflettono le fixture in mocks/fixtures/, derivate dai dati di seed del backend.
 *
 * The version of the OpenAPI document: 0.0.0-reference
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ErrorResponseError
 */
export interface ErrorResponseError {
  /**
   *
   * @type {string}
   * @memberof ErrorResponseError
   */
  code: string;
  /**
   *
   * @type {string}
   * @memberof ErrorResponseError
   */
  message: string;
  /**
   *
   * @type {any}
   * @memberof ErrorResponseError
   */
  details?: any | null;
}

/**
 * Check if a given object implements the ErrorResponseError interface.
 */
export function instanceOfErrorResponseError(
  value: object
): value is ErrorResponseError {
  if (!('code' in value) || value['code'] === undefined) return false;
  return !(!('message' in value) || value['message'] === undefined);
}

export function ErrorResponseErrorFromJSON(json: any): ErrorResponseError {
  return ErrorResponseErrorFromJSONTyped(json, false);
}

export function ErrorResponseErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ErrorResponseError {
  if (json == null) {
    return json;
  }
  return {
    code: json['code'],
    message: json['message'],
    details: json['details'] == null ? undefined : json['details'],
  };
}

export function ErrorResponseErrorToJSON(json: any): ErrorResponseError {
  return ErrorResponseErrorToJSONTyped(json, false);
}

export function ErrorResponseErrorToJSONTyped(
  value?: ErrorResponseError | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    code: value['code'],
    message: value['message'],
    details: value['details'],
  };
}
