/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Scheduler BE — spec di riferimento (NON autoritativo)
 * Spec minimo di riferimento per sbloccare lo sviluppo frontend quando il backend non e\' ancora disponibile. NON e\' la fonte di verita\': appena il backend espone /openapi.json, questo file va abbandonato in favore di quello reale. I nomi dei campi qui riflettono le fixture in mocks/fixtures/, derivate dai dati di seed del backend.
 *
 * The version of the OpenAPI document: 0.0.0-reference
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Genere } from './Genere';
import {
  GenereFromJSON,
  GenereFromJSONTyped,
  GenereToJSON,
  GenereToJSONTyped,
} from './Genere';
import type { RatingEta } from './RatingEta';
import {
  RatingEtaFromJSON,
  RatingEtaFromJSONTyped,
  RatingEtaToJSON,
  RatingEtaToJSONTyped,
} from './RatingEta';

/**
 *
 * @export
 * @interface Film
 */
export interface Film {
  /**
   *
   * @type {number}
   * @memberof Film
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof Film
   */
  titolo: string;
  /**
   *
   * @type {number}
   * @memberof Film
   */
  durataMinuti: number;
  /**
   *
   * @type {Genere}
   * @memberof Film
   */
  genere: Genere;
  /**
   *
   * @type {RatingEta}
   * @memberof Film
   */
  ratingEta: RatingEta;
}

/**
 * Check if a given object implements the Film interface.
 */
export function instanceOfFilm(value: object): value is Film {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('titolo' in value) || value['titolo'] === undefined) return false;
  if (!('durataMinuti' in value) || value['durataMinuti'] === undefined)
    return false;
  if (!('genere' in value) || value['genere'] === undefined) return false;
  if (!('ratingEta' in value) || value['ratingEta'] === undefined) return false;
  return true;
}

export function FilmFromJSON(json: any): Film {
  return FilmFromJSONTyped(json, false);
}

export function FilmFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Film {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    titolo: json['titolo'],
    durataMinuti: json['durataMinuti'],
    genere: GenereFromJSON(json['genere']),
    ratingEta: RatingEtaFromJSON(json['ratingEta']),
  };
}

export function FilmToJSON(json: any): Film {
  return FilmToJSONTyped(json, false);
}

export function FilmToJSONTyped(
  value?: Film | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    titolo: value['titolo'],
    durataMinuti: value['durataMinuti'],
    genere: GenereToJSON(value['genere']),
    ratingEta: RatingEtaToJSON(value['ratingEta']),
  };
}
