/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Scheduler BE — spec di riferimento (NON autoritativo)
 * Spec minimo di riferimento per sbloccare lo sviluppo frontend quando il backend non e\' ancora disponibile. NON e\' la fonte di verita\': appena il backend espone /openapi.json, questo file va abbandonato in favore di quello reale. I nomi dei campi qui riflettono le fixture in mocks/fixtures/, derivate dai dati di seed del backend.
 *
 * The version of the OpenAPI document: 0.0.0-reference
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Film } from './Film';
import { FilmFromJSON, FilmToJSON } from './Film';

/**
 *
 * @export
 * @interface FilmsGet200Response
 */
export interface FilmsGet200Response {
  /**
   *
   * @type {Array<Film>}
   * @memberof FilmsGet200Response
   */
  items: Array<Film>;
  /**
   *
   * @type {number}
   * @memberof FilmsGet200Response
   */
  total: number;
  /**
   *
   * @type {number}
   * @memberof FilmsGet200Response
   */
  page?: number;
  /**
   *
   * @type {number}
   * @memberof FilmsGet200Response
   */
  pageSize?: number;
}

/**
 * Check if a given object implements the FilmsGet200Response interface.
 */
export function instanceOfFilmsGet200Response(
  value: object
): value is FilmsGet200Response {
  if (!('items' in value) || value['items'] === undefined) return false;
  return !(!('total' in value) || value['total'] === undefined);
}

export function FilmsGet200ResponseFromJSON(json: any): FilmsGet200Response {
  return FilmsGet200ResponseFromJSONTyped(json, false);
}

export function FilmsGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): FilmsGet200Response {
  if (json == null) {
    return json;
  }
  return {
    items: (json['items'] as Array<any>).map(FilmFromJSON),
    total: json['total'],
    page: json['page'] == null ? undefined : json['page'],
    pageSize: json['pageSize'] == null ? undefined : json['pageSize'],
  };
}

export function FilmsGet200ResponseToJSON(json: any): FilmsGet200Response {
  return FilmsGet200ResponseToJSONTyped(json, false);
}

export function FilmsGet200ResponseToJSONTyped(
  value?: FilmsGet200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    items: (value['items'] as Array<any>).map(FilmToJSON),
    total: value['total'],
    page: value['page'],
    pageSize: value['pageSize'],
  };
}
