/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Scheduler BE — spec di riferimento (NON autoritativo)
 * Spec minimo di riferimento per sbloccare lo sviluppo frontend quando il backend non e\' ancora disponibile. NON e\' la fonte di verita\': appena il backend espone /openapi.json, questo file va abbandonato in favore di quello reale. I nomi dei campi qui riflettono le fixture in mocks/fixtures/, derivate dai dati di seed del backend.
 *
 * The version of the OpenAPI document: 0.0.0-reference
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Genere } from './Genere';
import { GenereFromJSON, GenereToJSON } from './Genere';
import type { RatingEta } from './RatingEta';
import { RatingEtaFromJSON, RatingEtaToJSON } from './RatingEta';

/**
 *
 * @export
 * @interface FilmInput
 */
export interface FilmInput {
  /**
   *
   * @type {string}
   * @memberof FilmInput
   */
  titolo: string;
  /**
   *
   * @type {number}
   * @memberof FilmInput
   */
  durataMinuti: number;
  /**
   *
   * @type {Genere}
   * @memberof FilmInput
   */
  genere: Genere;
  /**
   *
   * @type {RatingEta}
   * @memberof FilmInput
   */
  ratingEta: RatingEta;
}

/**
 * Check if a given object implements the FilmInput interface.
 */
export function instanceOfFilmInput(value: object): value is FilmInput {
  if (!('titolo' in value) || value['titolo'] === undefined) return false;
  if (!('durataMinuti' in value) || value['durataMinuti'] === undefined)
    return false;
  if (!('genere' in value) || value['genere'] === undefined) return false;
  return !(!('ratingEta' in value) || value['ratingEta'] === undefined);
}

export function FilmInputFromJSON(json: any): FilmInput {
  return FilmInputFromJSONTyped(json, false);
}

export function FilmInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): FilmInput {
  if (json == null) {
    return json;
  }
  return {
    titolo: json['titolo'],
    durataMinuti: json['durataMinuti'],
    genere: GenereFromJSON(json['genere']),
    ratingEta: RatingEtaFromJSON(json['ratingEta']),
  };
}

export function FilmInputToJSON(json: any): FilmInput {
  return FilmInputToJSONTyped(json, false);
}

export function FilmInputToJSONTyped(
  value?: FilmInput | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    titolo: value['titolo'],
    durataMinuti: value['durataMinuti'],
    genere: GenereToJSON(value['genere']),
    ratingEta: RatingEtaToJSON(value['ratingEta']),
  };
}
