/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Scheduler BE — spec di riferimento (NON autoritativo)
 * Spec minimo di riferimento per sbloccare lo sviluppo frontend quando il backend non e\' ancora disponibile. NON e\' la fonte di verita\': appena il backend espone /openapi.json, questo file va abbandonato in favore di quello reale. I nomi dei campi qui riflettono le fixture in mocks/fixtures/, derivate dai dati di seed del backend.
 *
 * The version of the OpenAPI document: 0.0.0-reference
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const Genere = {
  Azione: 'Azione',
  Animazione: 'Animazione',
  Commedia: 'Commedia',
  Documentario: 'Documentario',
  Drammatico: 'Drammatico',
  Fantascienza: 'Fantascienza',
  Horror: 'Horror',
  Romantico: 'Romantico',
  Thriller: 'Thriller',
} as const;
export type Genere = (typeof Genere)[keyof typeof Genere];

export function instanceOfGenere(value: any): boolean {
  for (const key in Genere) {
    if (Object.prototype.hasOwnProperty.call(Genere, key)) {
      if (Genere[key as keyof typeof Genere] === value) {
        return true;
      }
    }
  }
  return false;
}

export function GenereFromJSON(json: any): Genere {
  return GenereFromJSONTyped(json, false);
}

export function GenereFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Genere {
  return json as Genere;
}

export function GenereToJSON(value?: Genere | null): any {
  return value as any;
}

export function GenereToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean
): Genere {
  return value as Genere;
}
