/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Scheduler BE — spec di riferimento (NON autoritativo)
 * Spec minimo di riferimento per sbloccare lo sviluppo frontend quando il backend non e\' ancora disponibile. NON e\' la fonte di verita\': appena il backend espone /openapi.json, questo file va abbandonato in favore di quello reale. I nomi dei campi qui riflettono le fixture in mocks/fixtures/, derivate dai dati di seed del backend.
 *
 * The version of the OpenAPI document: 0.0.0-reference
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface HealthGet200Response
 */
export interface HealthGet200Response {
  /**
   *
   * @type {string}
   * @memberof HealthGet200Response
   */
  status: string;
}

/**
 * Check if a given object implements the HealthGet200Response interface.
 */
export function instanceOfHealthGet200Response(
  value: object
): value is HealthGet200Response {
  if (!('status' in value) || value['status'] === undefined) return false;
  return true;
}

export function HealthGet200ResponseFromJSON(json: any): HealthGet200Response {
  return HealthGet200ResponseFromJSONTyped(json, false);
}

export function HealthGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): HealthGet200Response {
  if (json == null) {
    return json;
  }
  return {
    status: json['status'],
  };
}

export function HealthGet200ResponseToJSON(json: any): HealthGet200Response {
  return HealthGet200ResponseToJSONTyped(json, false);
}

export function HealthGet200ResponseToJSONTyped(
  value?: HealthGet200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    status: value['status'],
  };
}
