/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Scheduler BE — spec di riferimento (NON autoritativo)
 * Spec minimo di riferimento per sbloccare lo sviluppo frontend quando il backend non e\' ancora disponibile. NON e\' la fonte di verita\': appena il backend espone /openapi.json, questo file va abbandonato in favore di quello reale. I nomi dei campi qui riflettono le fixture in mocks/fixtures/, derivate dai dati di seed del backend.
 *
 * The version of the OpenAPI document: 0.0.0-reference
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface LoginInput
 */
export interface LoginInput {
  /**
   *
   * @type {string}
   * @memberof LoginInput
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof LoginInput
   */
  password: string;
}

/**
 * Check if a given object implements the LoginInput interface.
 */
export function instanceOfLoginInput(value: object): value is LoginInput {
  if (!('email' in value) || value['email'] === undefined) return false;
  return !(!('password' in value) || value['password'] === undefined);
}

export function LoginInputFromJSON(json: any): LoginInput {
  return LoginInputFromJSONTyped(json, false);
}

export function LoginInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): LoginInput {
  if (json == null) {
    return json;
  }
  return {
    email: json['email'],
    password: json['password'],
  };
}

export function LoginInputToJSON(json: any): LoginInput {
  return LoginInputToJSONTyped(json, false);
}

export function LoginInputToJSONTyped(
  value?: LoginInput | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    email: value['email'],
    password: value['password'],
  };
}
