/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Scheduler BE — spec di riferimento (NON autoritativo)
 * Spec minimo di riferimento per sbloccare lo sviluppo frontend quando il backend non e\' ancora disponibile. NON e\' la fonte di verita\': appena il backend espone /openapi.json, questo file va abbandonato in favore di quello reale. I nomi dei campi qui riflettono le fixture in mocks/fixtures/, derivate dai dati di seed del backend.
 *
 * The version of the OpenAPI document: 0.0.0-reference
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface OccupazioneProiezione
 */
export interface OccupazioneProiezione {
  /**
   *
   * @type {number}
   * @memberof OccupazioneProiezione
   */
  proiezioneId: number;
  /**
   *
   * @type {number}
   * @memberof OccupazioneProiezione
   */
  salaId: number;
  /**
   *
   * @type {Date}
   * @memberof OccupazioneProiezione
   */
  dataOraInizio: Date;
  /**
   *
   * @type {number}
   * @memberof OccupazioneProiezione
   */
  capienza: number;
  /**
   *
   * @type {number}
   * @memberof OccupazioneProiezione
   */
  postiPrenotati: number;
  /**
   *
   * @type {number}
   * @memberof OccupazioneProiezione
   */
  percentualeOccupazione: number;
}

/**
 * Check if a given object implements the OccupazioneProiezione interface.
 */
export function instanceOfOccupazioneProiezione(
  value: object
): value is OccupazioneProiezione {
  if (!('proiezioneId' in value) || value['proiezioneId'] === undefined)
    return false;
  if (!('salaId' in value) || value['salaId'] === undefined) return false;
  if (!('dataOraInizio' in value) || value['dataOraInizio'] === undefined)
    return false;
  if (!('capienza' in value) || value['capienza'] === undefined) return false;
  if (!('postiPrenotati' in value) || value['postiPrenotati'] === undefined)
    return false;
  return !(
    !('percentualeOccupazione' in value) ||
    value['percentualeOccupazione'] === undefined
  );
}

export function OccupazioneProiezioneFromJSON(
  json: any
): OccupazioneProiezione {
  return OccupazioneProiezioneFromJSONTyped(json, false);
}

export function OccupazioneProiezioneFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): OccupazioneProiezione {
  if (json == null) {
    return json;
  }
  return {
    proiezioneId: json['proiezioneId'],
    salaId: json['salaId'],
    dataOraInizio: new Date(json['dataOraInizio']),
    capienza: json['capienza'],
    postiPrenotati: json['postiPrenotati'],
    percentualeOccupazione: json['percentualeOccupazione'],
  };
}

export function OccupazioneProiezioneToJSON(json: any): OccupazioneProiezione {
  return OccupazioneProiezioneToJSONTyped(json, false);
}

export function OccupazioneProiezioneToJSONTyped(
  value?: OccupazioneProiezione | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    proiezioneId: value['proiezioneId'],
    salaId: value['salaId'],
    dataOraInizio: value['dataOraInizio'].toISOString(),
    capienza: value['capienza'],
    postiPrenotati: value['postiPrenotati'],
    percentualeOccupazione: value['percentualeOccupazione'],
  };
}
