/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Scheduler BE — spec di riferimento (NON autoritativo)
 * Spec minimo di riferimento per sbloccare lo sviluppo frontend quando il backend non e\' ancora disponibile. NON e\' la fonte di verita\': appena il backend espone /openapi.json, questo file va abbandonato in favore di quello reale. I nomi dei campi qui riflettono le fixture in mocks/fixtures/, derivate dai dati di seed del backend.
 *
 * The version of the OpenAPI document: 0.0.0-reference
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Posto
 */
export interface Posto {
  /**
   *
   * @type {number}
   * @memberof Posto
   */
  riga: number;
  /**
   *
   * @type {number}
   * @memberof Posto
   */
  colonna: number;
}

/**
 * Check if a given object implements the Posto interface.
 */
export function instanceOfPosto(value: object): value is Posto {
  if (!('riga' in value) || value['riga'] === undefined) return false;
  if (!('colonna' in value) || value['colonna'] === undefined) return false;
  return true;
}

export function PostoFromJSON(json: any): Posto {
  return PostoFromJSONTyped(json, false);
}

export function PostoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Posto {
  if (json == null) {
    return json;
  }
  return {
    riga: json['riga'],
    colonna: json['colonna'],
  };
}

export function PostoToJSON(json: any): Posto {
  return PostoToJSONTyped(json, false);
}

export function PostoToJSONTyped(
  value?: Posto | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    riga: value['riga'],
    colonna: value['colonna'],
  };
}
