/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Scheduler BE — spec di riferimento (NON autoritativo)
 * Spec minimo di riferimento per sbloccare lo sviluppo frontend quando il backend non e\' ancora disponibile. NON e\' la fonte di verita\': appena il backend espone /openapi.json, questo file va abbandonato in favore di quello reale. I nomi dei campi qui riflettono le fixture in mocks/fixtures/, derivate dai dati di seed del backend.
 *
 * The version of the OpenAPI document: 0.0.0-reference
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Posto } from './Posto';
import {
  PostoFromJSON,
  PostoFromJSONTyped,
  PostoToJSON,
  PostoToJSONTyped,
} from './Posto';
import type { StatoPrenotazione } from './StatoPrenotazione';
import {
  StatoPrenotazioneFromJSON,
  StatoPrenotazioneFromJSONTyped,
  StatoPrenotazioneToJSON,
  StatoPrenotazioneToJSONTyped,
} from './StatoPrenotazione';

/**
 *
 * @export
 * @interface Prenotazione
 */
export interface Prenotazione {
  /**
   *
   * @type {number}
   * @memberof Prenotazione
   */
  id: number;
  /**
   *
   * @type {number}
   * @memberof Prenotazione
   */
  proiezioneId: number;
  /**
   *
   * @type {number}
   * @memberof Prenotazione
   */
  utenteId: number;
  /**
   *
   * @type {StatoPrenotazione}
   * @memberof Prenotazione
   */
  stato: StatoPrenotazione;
  /**
   *
   * @type {Date}
   * @memberof Prenotazione
   */
  createdAt: Date;
  /**
   *
   * @type {Array<Posto>}
   * @memberof Prenotazione
   */
  posti: Array<Posto>;
}

/**
 * Check if a given object implements the Prenotazione interface.
 */
export function instanceOfPrenotazione(value: object): value is Prenotazione {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('proiezioneId' in value) || value['proiezioneId'] === undefined)
    return false;
  if (!('utenteId' in value) || value['utenteId'] === undefined) return false;
  if (!('stato' in value) || value['stato'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('posti' in value) || value['posti'] === undefined) return false;
  return true;
}

export function PrenotazioneFromJSON(json: any): Prenotazione {
  return PrenotazioneFromJSONTyped(json, false);
}

export function PrenotazioneFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Prenotazione {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    proiezioneId: json['proiezioneId'],
    utenteId: json['utenteId'],
    stato: StatoPrenotazioneFromJSON(json['stato']),
    createdAt: new Date(json['createdAt']),
    posti: (json['posti'] as Array<any>).map(PostoFromJSON),
  };
}

export function PrenotazioneToJSON(json: any): Prenotazione {
  return PrenotazioneToJSONTyped(json, false);
}

export function PrenotazioneToJSONTyped(
  value?: Prenotazione | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    proiezioneId: value['proiezioneId'],
    utenteId: value['utenteId'],
    stato: StatoPrenotazioneToJSON(value['stato']),
    createdAt: value['createdAt'].toISOString(),
    posti: (value['posti'] as Array<any>).map(PostoToJSON),
  };
}
