/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Scheduler BE — spec di riferimento (NON autoritativo)
 * Spec minimo di riferimento per sbloccare lo sviluppo frontend quando il backend non e\' ancora disponibile. NON e\' la fonte di verita\': appena il backend espone /openapi.json, questo file va abbandonato in favore di quello reale. I nomi dei campi qui riflettono le fixture in mocks/fixtures/, derivate dai dati di seed del backend.
 *
 * The version of the OpenAPI document: 0.0.0-reference
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Sala } from './Sala';
import { SalaFromJSON, SalaToJSON } from './Sala';
import type { Film } from './Film';
import { FilmFromJSON, FilmToJSON } from './Film';

/**
 *
 * @export
 * @interface Proiezione
 */
export interface Proiezione {
  /**
   *
   * @type {number}
   * @memberof Proiezione
   */
  id: number;
  /**
   *
   * @type {number}
   * @memberof Proiezione
   */
  filmId: number;
  /**
   *
   * @type {number}
   * @memberof Proiezione
   */
  salaId: number;
  /**
   *
   * @type {Date}
   * @memberof Proiezione
   */
  dataOraInizio: Date;
  /**
   *
   * @type {Date}
   * @memberof Proiezione
   */
  dataOraFine: Date;
  /**
   *
   * @type {Film}
   * @memberof Proiezione
   */
  film?: Film;
  /**
   *
   * @type {Sala}
   * @memberof Proiezione
   */
  sala?: Sala;
}

/**
 * Check if a given object implements the Proiezione interface.
 */
export function instanceOfProiezione(value: object): value is Proiezione {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('filmId' in value) || value['filmId'] === undefined) return false;
  if (!('salaId' in value) || value['salaId'] === undefined) return false;
  if (!('dataOraInizio' in value) || value['dataOraInizio'] === undefined)
    return false;
  return !(!('dataOraFine' in value) || value['dataOraFine'] === undefined);
}

export function ProiezioneFromJSON(json: any): Proiezione {
  return ProiezioneFromJSONTyped(json, false);
}

export function ProiezioneFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Proiezione {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    filmId: json['filmId'],
    salaId: json['salaId'],
    dataOraInizio: new Date(json['dataOraInizio']),
    dataOraFine: new Date(json['dataOraFine']),
    film: json['film'] == null ? undefined : FilmFromJSON(json['film']),
    sala: json['sala'] == null ? undefined : SalaFromJSON(json['sala']),
  };
}

export function ProiezioneToJSON(json: any): Proiezione {
  return ProiezioneToJSONTyped(json, false);
}

export function ProiezioneToJSONTyped(
  value?: Proiezione | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    filmId: value['filmId'],
    salaId: value['salaId'],
    dataOraInizio: value['dataOraInizio'].toISOString(),
    dataOraFine: value['dataOraFine'].toISOString(),
    film: FilmToJSON(value['film']),
    sala: SalaToJSON(value['sala']),
  };
}
