/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Scheduler BE — spec di riferimento (NON autoritativo)
 * Spec minimo di riferimento per sbloccare lo sviluppo frontend quando il backend non e\' ancora disponibile. NON e\' la fonte di verita\': appena il backend espone /openapi.json, questo file va abbandonato in favore di quello reale. I nomi dei campi qui riflettono le fixture in mocks/fixtures/, derivate dai dati di seed del backend.
 *
 * The version of the OpenAPI document: 0.0.0-reference
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Posto } from './Posto';
import {
  PostoFromJSON,
  PostoFromJSONTyped,
  PostoToJSON,
  PostoToJSONTyped,
} from './Posto';

/**
 *
 * @export
 * @interface ProiezioniIdPrenotazioniPostRequest
 */
export interface ProiezioniIdPrenotazioniPostRequest {
  /**
   *
   * @type {Array<Posto>}
   * @memberof ProiezioniIdPrenotazioniPostRequest
   */
  posti: Array<Posto>;
}

/**
 * Check if a given object implements the ProiezioniIdPrenotazioniPostRequest interface.
 */
export function instanceOfProiezioniIdPrenotazioniPostRequest(
  value: object
): value is ProiezioniIdPrenotazioniPostRequest {
  if (!('posti' in value) || value['posti'] === undefined) return false;
  return true;
}

export function ProiezioniIdPrenotazioniPostRequestFromJSON(
  json: any
): ProiezioniIdPrenotazioniPostRequest {
  return ProiezioniIdPrenotazioniPostRequestFromJSONTyped(json, false);
}

export function ProiezioniIdPrenotazioniPostRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ProiezioniIdPrenotazioniPostRequest {
  if (json == null) {
    return json;
  }
  return {
    posti: (json['posti'] as Array<any>).map(PostoFromJSON),
  };
}

export function ProiezioniIdPrenotazioniPostRequestToJSON(
  json: any
): ProiezioniIdPrenotazioniPostRequest {
  return ProiezioniIdPrenotazioniPostRequestToJSONTyped(json, false);
}

export function ProiezioniIdPrenotazioniPostRequestToJSONTyped(
  value?: ProiezioniIdPrenotazioniPostRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    posti: (value['posti'] as Array<any>).map(PostoToJSON),
  };
}
