/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Scheduler BE — spec di riferimento (NON autoritativo)
 * Spec minimo di riferimento per sbloccare lo sviluppo frontend quando il backend non e\' ancora disponibile. NON e\' la fonte di verita\': appena il backend espone /openapi.json, questo file va abbandonato in favore di quello reale. I nomi dei campi qui riflettono le fixture in mocks/fixtures/, derivate dai dati di seed del backend.
 *
 * The version of the OpenAPI document: 0.0.0-reference
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ProiezioneInput
 */
export interface ProiezioneInput {
  /**
   *
   * @type {number}
   * @memberof ProiezioneInput
   */
  filmId: number;
  /**
   *
   * @type {number}
   * @memberof ProiezioneInput
   */
  salaId: number;
  /**
   *
   * @type {Date}
   * @memberof ProiezioneInput
   */
  dataOraInizio: Date;
}

/**
 * Check if a given object implements the ProiezioneInput interface.
 */
export function instanceOfProiezioneInput(
  value: object
): value is ProiezioneInput {
  if (!('filmId' in value) || value['filmId'] === undefined) return false;
  if (!('salaId' in value) || value['salaId'] === undefined) return false;
  if (!('dataOraInizio' in value) || value['dataOraInizio'] === undefined)
    return false;
  return true;
}

export function ProiezioneInputFromJSON(json: any): ProiezioneInput {
  return ProiezioneInputFromJSONTyped(json, false);
}

export function ProiezioneInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ProiezioneInput {
  if (json == null) {
    return json;
  }
  return {
    filmId: json['filmId'],
    salaId: json['salaId'],
    dataOraInizio: new Date(json['dataOraInizio']),
  };
}

export function ProiezioneInputToJSON(json: any): ProiezioneInput {
  return ProiezioneInputToJSONTyped(json, false);
}

export function ProiezioneInputToJSONTyped(
  value?: ProiezioneInput | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    filmId: value['filmId'],
    salaId: value['salaId'],
    dataOraInizio: value['dataOraInizio'].toISOString(),
  };
}
