/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Scheduler BE — spec di riferimento (NON autoritativo)
 * Spec minimo di riferimento per sbloccare lo sviluppo frontend quando il backend non e\' ancora disponibile. NON e\' la fonte di verita\': appena il backend espone /openapi.json, questo file va abbandonato in favore di quello reale. I nomi dei campi qui riflettono le fixture in mocks/fixtures/, derivate dai dati di seed del backend.
 *
 * The version of the OpenAPI document: 0.0.0-reference
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const RatingEta = {
  T: 'T',
  _14: '14+',
  _18: '18+',
} as const;
export type RatingEta = (typeof RatingEta)[keyof typeof RatingEta];

export function instanceOfRatingEta(value: any): boolean {
  for (const key in RatingEta) {
    if (Object.prototype.hasOwnProperty.call(RatingEta, key)) {
      if (RatingEta[key as keyof typeof RatingEta] === value) {
        return true;
      }
    }
  }
  return false;
}

export function RatingEtaFromJSON(json: any): RatingEta {
  return RatingEtaFromJSONTyped(json, false);
}

export function RatingEtaFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): RatingEta {
  return json as RatingEta;
}

export function RatingEtaToJSON(value?: RatingEta | null): any {
  return value as any;
}

export function RatingEtaToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean
): RatingEta {
  return value as RatingEta;
}
