/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Scheduler BE — spec di riferimento (NON autoritativo)
 * Spec minimo di riferimento per sbloccare lo sviluppo frontend quando il backend non e\' ancora disponibile. NON e\' la fonte di verita\': appena il backend espone /openapi.json, questo file va abbandonato in favore di quello reale. I nomi dei campi qui riflettono le fixture in mocks/fixtures/, derivate dai dati di seed del backend.
 *
 * The version of the OpenAPI document: 0.0.0-reference
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface RegisterInput
 */
export interface RegisterInput {
  /**
   *
   * @type {string}
   * @memberof RegisterInput
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof RegisterInput
   */
  password: string;
  /**
   *
   * @type {string}
   * @memberof RegisterInput
   */
  nome: string;
  /**
   *
   * @type {string}
   * @memberof RegisterInput
   */
  cognome: string;
}

/**
 * Check if a given object implements the RegisterInput interface.
 */
export function instanceOfRegisterInput(value: object): value is RegisterInput {
  if (!('email' in value) || value['email'] === undefined) return false;
  if (!('password' in value) || value['password'] === undefined) return false;
  if (!('nome' in value) || value['nome'] === undefined) return false;
  return !(!('cognome' in value) || value['cognome'] === undefined);
}

export function RegisterInputFromJSON(json: any): RegisterInput {
  return RegisterInputFromJSONTyped(json, false);
}

export function RegisterInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): RegisterInput {
  if (json == null) {
    return json;
  }
  return {
    email: json['email'],
    password: json['password'],
    nome: json['nome'],
    cognome: json['cognome'],
  };
}

export function RegisterInputToJSON(json: any): RegisterInput {
  return RegisterInputToJSONTyped(json, false);
}

export function RegisterInputToJSONTyped(
  value?: RegisterInput | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    email: value['email'],
    password: value['password'],
    nome: value['nome'],
    cognome: value['cognome'],
  };
}
