/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Scheduler BE — spec di riferimento (NON autoritativo)
 * Spec minimo di riferimento per sbloccare lo sviluppo frontend quando il backend non e\' ancora disponibile. NON e\' la fonte di verita\': appena il backend espone /openapi.json, questo file va abbandonato in favore di quello reale. I nomi dei campi qui riflettono le fixture in mocks/fixtures/, derivate dai dati di seed del backend.
 *
 * The version of the OpenAPI document: 0.0.0-reference
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const Ruolo = {
  Customer: 'customer',
  Admin: 'admin',
} as const;
export type Ruolo = (typeof Ruolo)[keyof typeof Ruolo];

export function instanceOfRuolo(value: any): boolean {
  for (const key in Ruolo) {
    if (Object.prototype.hasOwnProperty.call(Ruolo, key)) {
      if (Ruolo[key as keyof typeof Ruolo] === value) {
        return true;
      }
    }
  }
  return false;
}

export function RuoloFromJSON(json: any): Ruolo {
  return RuoloFromJSONTyped(json, false);
}

export function RuoloFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Ruolo {
  return json as Ruolo;
}

export function RuoloToJSON(value?: Ruolo | null): any {
  return value as any;
}

export function RuoloToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean
): Ruolo {
  return value as Ruolo;
}
