/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Scheduler BE — spec di riferimento (NON autoritativo)
 * Spec minimo di riferimento per sbloccare lo sviluppo frontend quando il backend non e\' ancora disponibile. NON e\' la fonte di verita\': appena il backend espone /openapi.json, questo file va abbandonato in favore di quello reale. I nomi dei campi qui riflettono le fixture in mocks/fixtures/, derivate dai dati di seed del backend.
 *
 * The version of the OpenAPI document: 0.0.0-reference
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Sala
 */
export interface Sala {
  /**
   *
   * @type {number}
   * @memberof Sala
   */
  id: number;
  /**
   *
   * @type {number}
   * @memberof Sala
   */
  cinemaId: number;
  /**
   *
   * @type {string}
   * @memberof Sala
   */
  nome: string;
  /**
   *
   * @type {number}
   * @memberof Sala
   */
  righe: number;
  /**
   *
   * @type {number}
   * @memberof Sala
   */
  colonne: number;
  /**
   *
   * @type {number}
   * @memberof Sala
   */
  capienza: number;
}

/**
 * Check if a given object implements the Sala interface.
 */
export function instanceOfSala(value: object): value is Sala {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('cinemaId' in value) || value['cinemaId'] === undefined) return false;
  if (!('nome' in value) || value['nome'] === undefined) return false;
  if (!('righe' in value) || value['righe'] === undefined) return false;
  if (!('colonne' in value) || value['colonne'] === undefined) return false;
  return !(!('capienza' in value) || value['capienza'] === undefined);
}

export function SalaFromJSON(json: any): Sala {
  return SalaFromJSONTyped(json, false);
}

export function SalaFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Sala {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    cinemaId: json['cinemaId'],
    nome: json['nome'],
    righe: json['righe'],
    colonne: json['colonne'],
    capienza: json['capienza'],
  };
}

export function SalaToJSON(json: any): Sala {
  return SalaToJSONTyped(json, false);
}

export function SalaToJSONTyped(
  value?: Sala | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    cinemaId: value['cinemaId'],
    nome: value['nome'],
    righe: value['righe'],
    colonne: value['colonne'],
    capienza: value['capienza'],
  };
}
