/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Scheduler BE — spec di riferimento (NON autoritativo)
 * Spec minimo di riferimento per sbloccare lo sviluppo frontend quando il backend non e\' ancora disponibile. NON e\' la fonte di verita\': appena il backend espone /openapi.json, questo file va abbandonato in favore di quello reale. I nomi dei campi qui riflettono le fixture in mocks/fixtures/, derivate dai dati di seed del backend.
 *
 * The version of the OpenAPI document: 0.0.0-reference
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const StatoPrenotazione = {
  Pending: 'pending',
  Confirmed: 'confirmed',
  Cancelled: 'cancelled',
} as const;
export type StatoPrenotazione =
  (typeof StatoPrenotazione)[keyof typeof StatoPrenotazione];

export function instanceOfStatoPrenotazione(value: any): boolean {
  for (const key in StatoPrenotazione) {
    if (Object.prototype.hasOwnProperty.call(StatoPrenotazione, key)) {
      if (StatoPrenotazione[key as keyof typeof StatoPrenotazione] === value) {
        return true;
      }
    }
  }
  return false;
}

export function StatoPrenotazioneFromJSON(json: any): StatoPrenotazione {
  return StatoPrenotazioneFromJSONTyped(json, false);
}

export function StatoPrenotazioneFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): StatoPrenotazione {
  return json as StatoPrenotazione;
}

export function StatoPrenotazioneToJSON(value?: StatoPrenotazione | null): any {
  return value as any;
}

export function StatoPrenotazioneToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean
): StatoPrenotazione {
  return value as StatoPrenotazione;
}
