/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Scheduler BE — spec di riferimento (NON autoritativo)
 * Spec minimo di riferimento per sbloccare lo sviluppo frontend quando il backend non e\' ancora disponibile. NON e\' la fonte di verita\': appena il backend espone /openapi.json, questo file va abbandonato in favore di quello reale. I nomi dei campi qui riflettono le fixture in mocks/fixtures/, derivate dai dati di seed del backend.
 *
 * The version of the OpenAPI document: 0.0.0-reference
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Ruolo } from './Ruolo';
import {
  RuoloFromJSON,
  RuoloFromJSONTyped,
  RuoloToJSON,
  RuoloToJSONTyped,
} from './Ruolo';

/**
 *
 * @export
 * @interface Utente
 */
export interface Utente {
  /**
   *
   * @type {number}
   * @memberof Utente
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof Utente
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof Utente
   */
  nome: string;
  /**
   *
   * @type {string}
   * @memberof Utente
   */
  cognome: string;
  /**
   *
   * @type {Ruolo}
   * @memberof Utente
   */
  ruolo: Ruolo;
}

/**
 * Check if a given object implements the Utente interface.
 */
export function instanceOfUtente(value: object): value is Utente {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('email' in value) || value['email'] === undefined) return false;
  if (!('nome' in value) || value['nome'] === undefined) return false;
  if (!('cognome' in value) || value['cognome'] === undefined) return false;
  if (!('ruolo' in value) || value['ruolo'] === undefined) return false;
  return true;
}

export function UtenteFromJSON(json: any): Utente {
  return UtenteFromJSONTyped(json, false);
}

export function UtenteFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Utente {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    email: json['email'],
    nome: json['nome'],
    cognome: json['cognome'],
    ruolo: RuoloFromJSON(json['ruolo']),
  };
}

export function UtenteToJSON(json: any): Utente {
  return UtenteToJSONTyped(json, false);
}

export function UtenteToJSONTyped(
  value?: Utente | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    email: value['email'],
    nome: value['nome'],
    cognome: value['cognome'],
    ruolo: RuoloToJSON(value['ruolo']),
  };
}
